# Generated by Django 5.0 on 2023-12-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_name_seriesname_createname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterinfo',
            name='image',
            field=models.ImageField(upload_to='core/static/photos'),
        ),
        migrations.AlterField(
            model_name='seriesname',
            name='image',
            field=models.ImageField(upload_to='core/static/photos'),
        ),
    ]
