# Generated by Django 5.0 on 2023-12-22 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_characterinfo_image_alter_seriesname_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterinfo',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterinfo',
            name='quote',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characterinfo',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.seriesname'),
        ),
        migrations.AlterField(
            model_name='characterinfo',
            name='image',
            field=models.ImageField(upload_to='app/static/photos'),
        ),
    ]
