# Generated by Django 5.0 on 2023-12-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_character_characterinfo_seriesname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='characterinfo',
            name='planet',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
