# Generated by Django 5.0 on 2023-12-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_characterinfo_age_characterinfo_planet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesname',
            name='image',
            field=models.ImageField(upload_to='core/static/photos/icons'),
        ),
    ]
