# Generated by Django 5.0 on 2023-12-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_seriesname_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesname',
            name='link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
