# Generated by Django 5.0 on 2023-12-30 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_uuser_userseries_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('planet', models.CharField(max_length=255)),
                ('quote', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='app/static/photos')),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('seriesName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.userseries')),
            ],
        ),
    ]
